# -*- mode: ruby -*-
# vi: set ft=ruby :

number_of_workers = ENV.fetch("K3S_WORKERS", 1)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "master" do |master|
    master.vm.hostname = "master"

    master.vm.network :private_network, ip: "192.168.80.10", netmask: "255.255.255.0"

    master.vm.provision :shell, path: "scripts/master.sh"

    master.vm.provider :virtualbox do |vbox|
      vbox.name = "Ubuntu k3s-master"
      vbox.memory = "1024"
      vbox.cpus = "1"
    end
  end

  (1..number_of_workers).each do |worker_number|
    config.vm.define "worker-#{worker_number}" do |worker|
      worker.vm.hostname = "worker#{worker_number}"

      ip = worker_number + 100
      worker.vm.network :private_network, ip: "192.168.80.#{ip}", netmask: "255.255.255.0"

      worker.vm.provision :shell, path: "scripts/worker.sh"

      worker.vm.provider :virtualbox do |vbox|
        vbox.name = "Ubuntu k3s-worker-#{worker_number}"
        vbox.memory = "1024"
        vbox.cpus = "1"
      end
    end
  end
end
