# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "nimblelink-k3s" do |k3s|
    config.vm.network "forwarded_port", guest: 8001, host: 8001, auto_correct: true
    config.vm.network "forwarded_port", guest: 9110, host: 9110, auto_correct: true

    config.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-nimblelink-k3s"
      vb.memory = "1024"
      vb.cpus = "1"
    end

    args = []
    config.vm.provision "shell", path: "scripts/install_k3s.sh", args: args

    config.vm.provision "file", source: "../k3s", destination: "$HOME/k3s"
  end
end
