apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  labels:
    app: nimblelink
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimblelink
      tier: database
  template:
    metadata:
      labels:
        app: nimblelink
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: database-secret
